services:
  mysql:
    container_name: app_mysql
    image: mysql:5.7.22
    volumes:
      - ./docker-assets/mysql/data:/docker-entrypoint-initdb.d
    restart: always
    tty: true
    ports:
      - "3506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homework
  mongo:
    container_name: app_mongo
    image: mongo:3.6
    ports:
      - "10017:27017"
    environment:
      - MONGO_INITDB_DATABASE=homework
    volumes:
      - ./docker-assets/mongo/data:/home/mongo
      - ./docker-assets/mongo/scripts:/docker-entrypoint-initdb.d/
